/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CoolStuffRouteImport } from './routes/cool-stuff'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as BlogTrainsRouteImport } from './routes/blog.trains'
import { Route as BlogClimateRouteImport } from './routes/blog.climate'
import { Route as BlogAviationRouteImport } from './routes/blog.aviation'
import { Route as BlogAiSafetyRouteImport } from './routes/blog.ai-safety'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CoolStuffRoute = CoolStuffRouteImport.update({
  id: '/cool-stuff',
  path: '/cool-stuff',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const BlogTrainsRoute = BlogTrainsRouteImport.update({
  id: '/trains',
  path: '/trains',
  getParentRoute: () => BlogRoute,
} as any)
const BlogClimateRoute = BlogClimateRouteImport.update({
  id: '/climate',
  path: '/climate',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAviationRoute = BlogAviationRouteImport.update({
  id: '/aviation',
  path: '/aviation',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAiSafetyRoute = BlogAiSafetyRouteImport.update({
  id: '/ai-safety',
  path: '/ai-safety',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cool-stuff': typeof CoolStuffRoute
  '/games': typeof GamesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/travel': typeof TravelRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/ai-safety': typeof BlogAiSafetyRoute
  '/blog/aviation': typeof BlogAviationRoute
  '/blog/climate': typeof BlogClimateRoute
  '/blog/trains': typeof BlogTrainsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cool-stuff': typeof CoolStuffRoute
  '/games': typeof GamesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/travel': typeof TravelRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/ai-safety': typeof BlogAiSafetyRoute
  '/blog/aviation': typeof BlogAviationRoute
  '/blog/climate': typeof BlogClimateRoute
  '/blog/trains': typeof BlogTrainsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cool-stuff': typeof CoolStuffRoute
  '/games': typeof GamesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/travel': typeof TravelRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/ai-safety': typeof BlogAiSafetyRoute
  '/blog/aviation': typeof BlogAviationRoute
  '/blog/climate': typeof BlogClimateRoute
  '/blog/trains': typeof BlogTrainsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/cool-stuff'
    | '/games'
    | '/projects'
    | '/sitemap.xml'
    | '/travel'
    | '/blog/$slug'
    | '/blog/ai-safety'
    | '/blog/aviation'
    | '/blog/climate'
    | '/blog/trains'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/cool-stuff'
    | '/games'
    | '/projects'
    | '/sitemap.xml'
    | '/travel'
    | '/blog/$slug'
    | '/blog/ai-safety'
    | '/blog/aviation'
    | '/blog/climate'
    | '/blog/trains'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/cool-stuff'
    | '/games'
    | '/projects'
    | '/sitemap.xml'
    | '/travel'
    | '/blog/$slug'
    | '/blog/ai-safety'
    | '/blog/aviation'
    | '/blog/climate'
    | '/blog/trains'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CoolStuffRoute: typeof CoolStuffRoute
  GamesRoute: typeof GamesRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TravelRoute: typeof TravelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cool-stuff': {
      id: '/cool-stuff'
      path: '/cool-stuff'
      fullPath: '/cool-stuff'
      preLoaderRoute: typeof CoolStuffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/blog/trains': {
      id: '/blog/trains'
      path: '/trains'
      fullPath: '/blog/trains'
      preLoaderRoute: typeof BlogTrainsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/climate': {
      id: '/blog/climate'
      path: '/climate'
      fullPath: '/blog/climate'
      preLoaderRoute: typeof BlogClimateRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/aviation': {
      id: '/blog/aviation'
      path: '/aviation'
      fullPath: '/blog/aviation'
      preLoaderRoute: typeof BlogAviationRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/ai-safety': {
      id: '/blog/ai-safety'
      path: '/ai-safety'
      fullPath: '/blog/ai-safety'
      preLoaderRoute: typeof BlogAiSafetyRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAiSafetyRoute: typeof BlogAiSafetyRoute
  BlogAviationRoute: typeof BlogAviationRoute
  BlogClimateRoute: typeof BlogClimateRoute
  BlogTrainsRoute: typeof BlogTrainsRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogAiSafetyRoute: BlogAiSafetyRoute,
  BlogAviationRoute: BlogAviationRoute,
  BlogClimateRoute: BlogClimateRoute,
  BlogTrainsRoute: BlogTrainsRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CoolStuffRoute: CoolStuffRoute,
  GamesRoute: GamesRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TravelRoute: TravelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
